function on_game_start()
    local fx		= placeable_explosive.FX_BY_SECTION
    local ex_type	= placeable_explosive.EXPLOSIVE_TYPE

    fx["ied_electro"] = 'ied_electro'
    fx["ied_gravy"]	= 'ied_gravy'
    fx["ied_burn"]	= 'ied_burn'
    fx["ied_acid"]	= 'ied_acid'
	
    ex_type["ied_electro"]	= game.translate_string("st_plant_explosive_remote_ied_electro")
    ex_type["ied_gravy"]	= game.translate_string("st_plant_explosive_remote_ied_gravy")
    ex_type["ied_burn"]		= game.translate_string("st_plant_explosive_remote_ied_burn")
    ex_type["ied_acid"]		= game.translate_string("st_plant_explosive_remote_ied_acid")
	
	-- printf("ze fx table\n%s", utils_data.print_table(placeable_explosive.FX_BY_SECTION, false, true))
	-- printf("ze section table\n%s", utils_data.print_table(placeable_explosive.EXPLOSIVE_TYPE, false, true))
	
end